version: '3'
services:
  db:
    container_name: actix-website_db
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=actix_website
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_HOST=db
        - DB_NAME=actix_website
        - DISCORD_HOOK_URL=
    restart: always
    ports:
    - "8080:8080"
